CREATE TABLE [dbo].[GTL_KEYTABLE]
(
[KEYNAME] [varchar] (32) NOT NULL,
[NEWKEY] [numeric] (15, 0) NOT NULL,
[EUSER] [varchar] (50) NULL,
[LASTUPDATEDON] [datetime] NULL,
[COMPANYID] [int] NOT NULL CONSTRAINT [DF__GTL_KEYTA__COMPA__3587F3E0] DEFAULT ((1))
)
GO
ALTER TABLE [dbo].[GTL_KEYTABLE] ADD CONSTRAINT [PK_GTL_KEYTABLE] PRIMARY KEY CLUSTERED ([KEYNAME], [COMPANYID])
GO
