CREATE TABLE [dbo].[GTL_UserPassword]
(
[PASSWORDID] [int] NOT NULL IDENTITY(3, 1),
[COMPANYID] [int] NOT NULL,
[USERCODE] [nvarchar] (20) NULL,
[PWD] [nvarchar] (200) NULL
)
GO
ALTER TABLE [dbo].[GTL_UserPassword] ADD CONSTRAINT [PK_GTL_USERPASSWORD_PASSWORDID] PRIMARY KEY CLUSTERED ([COMPANYID], [PASSWORDID])
GO
