CREATE TABLE [dbo].[GTL_PasswordPolicy]
(
[LENGTH] [char] (1) NULL,
[LOWERCASE] [char] (1) NULL CONSTRAINT [DF__GTL_PASSW__LOWER__1E6F845E] DEFAULT ('N'),
[UPPERCASE] [char] (1) NULL CONSTRAINT [DF__GTL_PASSW__UPPER__1F63A897] DEFAULT ('N'),
[NUMERIC] [char] (1) NULL CONSTRAINT [DF__GTL_PASSW__NUMER__2057CCD0] DEFAULT ('N'),
[NONALPHANUMERIC] [char] (1) NULL CONSTRAINT [DF__GTL_PASSW__NONAL__214BF109] DEFAULT ('N'),
[COMPANYID] [numeric] (10, 0) NULL,
[LASTUPDATEDON] [datetime] NOT NULL CONSTRAINT [DF__GTL_PASSW__LASTU__22401542] DEFAULT (getdate()),
[EUSER] [nvarchar] (20) NULL,
[APPLYPWDPOLICY] [char] (1) NULL,
[PKSlNo] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [dbo].[GTL_PasswordPolicy] ADD CONSTRAINT [GTL_PasswordPolicy_PKSlNo] PRIMARY KEY CLUSTERED ([PKSlNo])
GO
