CREATE TABLE [dbo].[GTL_WUserLocationsNew]
(
[USERID] [int] NOT NULL,
[COMPANYID] [int] NOT NULL CONSTRAINT [DF__GTL_WUSER__COMPA__0F2D40CE] DEFAULT ((1)),
[USERCODE] [nvarchar] (16) NOT NULL,
[LOCATIONID] [varchar] (max) NULL,
[REGIONID] [varchar] (5000) NULL,
[LANGID] [int] NOT NULL,
[ACCESSLOCATIONS] [varchar] (max) NULL,
[USERPROJECTS] [nvarchar] (4000) NULL,
[TOLOCATION] [nvarchar] (50) NULL,
[PKSlNo] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [dbo].[GTL_WUserLocationsNew] ADD CONSTRAINT [GTL_WUserLocationsNew_PKSlNo] PRIMARY KEY CLUSTERED ([PKSlNo])
GO
