CREATE TABLE [dbo].[GTL_Users]
(
[COMPANYID] [int] NOT NULL CONSTRAINT [DF__GTL_USERS__COMPA__00DF2177] DEFAULT ((1)),
[USERID] [int] NOT NULL,
[LANGID] [int] NOT NULL,
[USERCODE] [nvarchar] (50) NULL,
[USERNAME] [nvarchar] (128) NOT NULL,
[PASSWORD] [nvarchar] (100) NOT NULL,
[LOCATIONID] [int] NULL,
[EMAILID] [nvarchar] (128) NULL,
[EUSER] [nvarchar] (10) NULL,
[LASTUPDATEDON] [datetime] NOT NULL CONSTRAINT [DF__GTL_USERS__LASTU__01D345B0] DEFAULT (getdate()),
[PAYROLLACCESSRIGHTS] [nvarchar] (2) NOT NULL CONSTRAINT [DF__GTL_USERS__PAYRO__02C769E9] DEFAULT ('N'),
[REGION] [nchar] (8) NULL,
[TERMINATED] [nchar] (2) NULL CONSTRAINT [DF__GTL_USERS__TERMI__03BB8E22] DEFAULT ('N'),
[GROUPID] [numeric] (5, 0) NULL,
[TOLOCATION] [nvarchar] (100) NULL,
[FAX] [nvarchar] (200) NULL,
[TELEPHONENO] [nvarchar] (50) NULL,
[DEPARTMENT] [nvarchar] (200) NULL,
[ISWEBUSER] [nvarchar] (2) NOT NULL CONSTRAINT [DF__GTL_USERS__ISWEB__04AFB25B] DEFAULT ('N'),
[CHANGEPASSWORD] [varchar] (1) NULL,
[PASSWORDEXPIRE] [char] (1) NULL,
[EXPIREDAYS] [numeric] (4, 0) NULL,
[PASSWORDENABLEDDATE] [datetime] NULL,
[SIGNATURE] [image] NULL,
[MACHINEWISELOGIN] [char] (1) NULL,
[MACHINENAME] [nvarchar] (200) NULL,
[ENABLEPASSWORDCOUNT] [char] (1) NULL,
[PASSWORDCOUNT] [numeric] (4, 0) NULL,
[LOGINPROJECTID] [varchar] (4000) NULL,
[CORPUSER] [char] (1) NULL CONSTRAINT [DF__GTL_USERS__CORPU__05A3D694] DEFAULT ('N'),
[REGIONID] [int] NULL,
[TerminatedDate] [datetime] NULL,
[TerminatedReason] [nvarchar] (200) NULL,
[AccessInAllLocation] [char] (1) NULL,
[UserType] [varchar] (10) NULL CONSTRAINT [DF__GTL_USERS__UserT__3BCBA872] DEFAULT ('BRANCH'),
[BranchGroupId] [int] NULL CONSTRAINT [DF__GTL_USERS__Branc__3CBFCCAB] DEFAULT ((0)),
[MaxQueryLevel] [varchar] (20) NULL,
[CRMIsProcessed] [char] (1) NOT NULL CONSTRAINT [DF__GTL_Users__CRMIs__5E1FF51F] DEFAULT ('N'),
[IPAddress] [varchar] (100) NULL,
[OTP] [varchar] (50) NULL,
[OTPTime] [datetime] NULL,
[OTPEnabled] [char] (1) NOT NULL CONSTRAINT [DF__GTL_Users__OTPEn__5F141958] DEFAULT ('Y'),
[ShowDashBoard] [char] (1) NOT NULL CONSTRAINT [DF__GTL_Users__ShowD__60083D91] DEFAULT ('Y'),
[RoleIds] [varchar] (8000) NULL,
[SkipDataMasking] [varchar] (1) NULL,
[DOB] [datetime] NULL,
[CompanyState] [varchar] (100) NULL,
[Designation] [varchar] (150) NULL,
[Address1] [varchar] (200) NULL,
[Address2] [varchar] (200) NULL,
[Address3] [varchar] (200) NULL,
[PinCode] [varchar] (10) NULL,
[StateID] [int] NULL,
[CountryID] [int] NULL,
[District] [varchar] (100) NULL,
[City] [varchar] (100) NULL,
[OfficialMobileNo] [varchar] (25) NULL
)
GO
ALTER TABLE [dbo].[GTL_Users] ADD CONSTRAINT [PK_GTL_USERS] PRIMARY KEY CLUSTERED ([LANGID], [USERID], [COMPANYID])
GO
ALTER TABLE [dbo].[GTL_Users] ADD CONSTRAINT [UK_GTL_Users] UNIQUE NONCLUSTERED ([USERCODE])
GO
