CREATE TABLE [dbo].[GTL_UserRights]
(
[COMPANYID] [int] NOT NULL CONSTRAINT [DF__GTL_USERR__COMPA__793DFFAF] DEFAULT ((1)),
[GROUPID] [int] NOT NULL CONSTRAINT [DF__GTL_USERR__GROUP__7A3223E8] DEFAULT ((1)),
[PROJECTID] [int] NOT NULL CONSTRAINT [DF__GTL_USERR__PROJE__7B264821] DEFAULT ((0)),
[MODULEID] [int] NOT NULL,
[ADDRIGHT] [char] (1) NULL,
[MODIFYRIGHT] [char] (1) NULL,
[DELETERIGHT] [char] (1) NULL,
[PREVIEWRIGHT] [char] (1) NULL,
[MENUNAME] [varchar] (128) NULL CONSTRAINT [DF__GTL_USERR__MENUN__7C1A6C5A] DEFAULT ('Null'),
[PRINTRIGHT] [varchar] (1) NULL,
[EUSER] [varchar] (10) NOT NULL,
[LASTUPDATEDON] [datetime] NOT NULL CONSTRAINT [DF__GTL_USERR__LASTU__7D0E9093] DEFAULT (getdate()),
[SHOWMENU] [char] (1) NULL CONSTRAINT [DF__GTL_USERR__SHOWM__7E02B4CC] DEFAULT ('Y'),
[EXPORTRIGHT] [varchar] (1) NULL,
[SPECIALRIGHT] [varchar] (1) NULL
)
GO
ALTER TABLE [dbo].[GTL_UserRights] ADD CONSTRAINT [PK_GTL_USERRIGHTS] PRIMARY KEY CLUSTERED ([GROUPID], [MODULEID], [PROJECTID], [COMPANYID])
GO
