CREATE TABLE [dbo].[GTL_UserGroups]
(
[COMPANYID] [int] NOT NULL CONSTRAINT [DF__GTL_USERG__COMPA__72910220] DEFAULT ((1)),
[GROUPID] [numeric] (5, 0) NOT NULL,
[ISWEBUSER] [nvarchar] (1) NOT NULL CONSTRAINT [DF__GTL_USERG__ISWEB__73852659] DEFAULT ('N'),
[DESCRIPTION] [nvarchar] (128) NULL,
[LANGID] [int] NOT NULL,
[EUSER] [nvarchar] (20) NULL,
[LASTUPDATEDON] [datetime] NULL,
[ACCESSPROJECTID] [varchar] (1000) NULL,
[LevelID] [int] NULL,
[Remarks] [varchar] (4000) NULL,
[DepartmentID] [int] NULL
)
GO
ALTER TABLE [dbo].[GTL_UserGroups] ADD CONSTRAINT [PK_GTL_USERGROUPS] PRIMARY KEY CLUSTERED ([GROUPID], [COMPANYID], [LANGID])
GO
