CREATE TABLE [dbo].[DPS_Settings]
(
[NsdldefaultDPID] [varchar] (8) NULL,
[CdslDefaultDPID] [varchar] (8) NULL,
[MonthlyAccounting] [varchar] (1) NOT NULL CONSTRAINT [DF__DPS_Setti__Month__2C88998B] DEFAULT ('N'),
[TransMaxValue] [numeric] (15, 2) NOT NULL CONSTRAINT [DF__DPS_Setti__Trans__2D7CBDC4] DEFAULT ((500000)),
[MaxInstrAllowed] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__MaxIn__2E70E1FD] DEFAULT ((4)),
[MaxMultiClientInstrAllowed] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__MaxMu__2F650636] DEFAULT ((20)),
[DaysforDormant] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__Daysf__30592A6F] DEFAULT ((0)),
[DebittoFreezeAccount] [numeric] (18, 3) NOT NULL CONSTRAINT [DF__DPS_Setti__Debit__314D4EA8] DEFAULT ((0)),
[CdslMaxSignSize] [int] NULL,
[NsdlMaxSignSize] [int] NULL,
[HoldingforDebitclients] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__Holdi__324172E1] DEFAULT ((0)),
[BaseDate] [datetime] NULL,
[FreezLimit] [numeric] (15, 2) NOT NULL CONSTRAINT [DF__DPS_Setti__Freez__3335971A] DEFAULT ((0)),
[EODDateTime] [datetime] NULL,
[InitialSearchRows] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__Initi__3429BB53] DEFAULT ((10)),
[NSDLLogo] [image] NULL,
[CDSLLogo] [image] NULL,
[OtherDefaultDPID] [char] (8) NOT NULL CONSTRAINT [DF__DPS_Setti__Other__351DDF8C] DEFAULT ('IN000026'),
[DebitPenaltyMin] [int] NULL,
[DebitPenaltyPerc] [int] NULL,
[DebitPenaltyAC] [int] NULL,
[RemiserCommissionAC] [int] NULL,
[CompanyId] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__Compa__361203C5] DEFAULT ((1)),
[ProjectId] [int] NOT NULL CONSTRAINT [DF__DPS_Setti__Proje__370627FE] DEFAULT ((0)),
[DefaultLocationID] [int] NULL,
[ACTransferDeadlineTime] [char] (8) NULL,
[InterDPDeadlineTime] [char] (8) NULL,
[MaxInstrAllowed_Web] [int] NULL,
[SPARCServerName] [varchar] (100) NULL,
[DefaultCDSLExportUser] [varchar] (6) NULL,
[DefaultNSDLExportUser] [varchar] (6) NULL,
[DefaultSBBranchID] [int] NULL,
[CDSLLogoPath] [varchar] (1000) NULL,
[CompanyLogoPath] [varchar] (1000) NULL,
[InitialAMCChargeMode] [varchar] (10) NULL,
[NSDLLogoPath] [varchar] (1000) NULL,
[CDSLPANNo] [varchar] (10) NULL,
[CDSLServiceTaxNo] [varchar] (25) NULL,
[CDSLComplianceOfficer] [varchar] (100) NULL,
[CDSLComplianceEMailID] [varchar] (100) NULL,
[CDSLCompliancePhoneNo] [varchar] (25) NULL,
[CDSLSEBIRegNo] [varchar] (50) NULL,
[CDSLSMSRemarks] [varchar] (100) NULL,
[CDSLPOARemarks] [varchar] (100) NULL,
[CDSLDefaultPOAID] [varchar] (16) NULL,
[DocumentUploadPath] [varchar] (max) NULL,
[CheckHoldinginEntry] [char] (1) NULL,
[AMCHoldingLimit] [numeric] (18, 2) NULL,
[AMCLedgerLimit] [numeric] (18, 2) NULL,
[AMCTransactionLimit] [int] NULL,
[DPSystem_StartDate] [datetime] NULL,
[AutoApplicationNo] [char] (1) NULL,
[ApplicationPrefix] [varchar] (10) NULL,
[BrkAdjRefcode] [varchar] (16) NULL,
[InstallationType] [varchar] (50) NULL,
[TransferDebitFromDP] [char] (1) NULL,
[MultiNomineeRegNo] [char] (1) NULL,
[CCCompanyLogoPath] [varchar] (2000) NULL,
[CompanyLogoPathFormat2] [varchar] (1000) NULL,
[NSDLPANNo] [varchar] (10) NULL,
[NSDLServiceTaxNo] [varchar] (25) NULL,
[NSDLComplianceOfficer] [varchar] (100) NULL,
[NSDLComplianceEMailID] [varchar] (100) NULL,
[NSDLCompliancePhoneNo] [varchar] (100) NULL,
[NSDLSEBIRegNo] [varchar] (50) NULL,
[NSDLSMSRemarks] [varchar] (100) NULL,
[NSDLPOARemarks] [varchar] (100) NULL,
[NSDLDefaultPOAID] [varchar] (16) NULL,
[PanVerificationURL] [varchar] (500) NULL,
[CCGblPwd] [varchar] (500) NULL,
[DPIDPrefix] [varchar] (3) NULL,
[RestServicePath] [varchar] (max) NULL,
[MPledgeEffectiveDate] [datetime] NULL,
[CDSLDefaultGPABPAFlag] [varchar] (10) NULL,
[PKSlNo] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [dbo].[DPS_Settings] ADD CONSTRAINT [DPS_Settings_PKSlNo] PRIMARY KEY CLUSTERED ([PKSlNo])
GO
