CREATE TABLE [dbo].[GTL_Users_Log]
(
[PK_SlNo] [int] NOT NULL IDENTITY(1, 1),
[COMPANYID] [int] NOT NULL,
[USERID] [int] NOT NULL,
[LANGID] [int] NOT NULL,
[USERCODE] [nvarchar] (50) NULL,
[USERNAME] [nvarchar] (128) NOT NULL,
[PASSWORD] [nvarchar] (100) NOT NULL,
[LOCATIONID] [int] NULL,
[EMAILID] [nvarchar] (128) NULL,
[EUSER] [nvarchar] (10) NULL,
[LASTUPDATEDON] [datetime] NOT NULL,
[PAYROLLACCESSRIGHTS] [nvarchar] (2) NOT NULL,
[REGION] [nchar] (8) NULL,
[TERMINATED] [nchar] (2) NULL,
[GROUPID] [numeric] (5, 0) NULL,
[TOLOCATION] [nvarchar] (100) NULL,
[FAX] [nvarchar] (200) NULL,
[TELEPHONENO] [nvarchar] (50) NULL,
[DEPARTMENT] [nvarchar] (200) NULL,
[ISWEBUSER] [nvarchar] (2) NOT NULL,
[CHANGEPASSWORD] [varchar] (1) NULL,
[PASSWORDEXPIRE] [char] (1) NULL,
[EXPIREDAYS] [numeric] (4, 0) NULL,
[PASSWORDENABLEDDATE] [datetime] NULL,
[SIGNATURE] [image] NULL,
[MACHINEWISELOGIN] [char] (1) NULL,
[MACHINENAME] [nvarchar] (200) NULL,
[ENABLEPASSWORDCOUNT] [char] (1) NULL,
[PASSWORDCOUNT] [numeric] (4, 0) NULL,
[LOGINPROJECTID] [varchar] (4000) NULL,
[CORPUSER] [char] (1) NULL,
[REGIONID] [int] NULL,
[TerminatedDate] [datetime] NULL,
[TerminatedReason] [nvarchar] (200) NULL,
[AccessInAllLocation] [char] (1) NULL,
[UserType] [varchar] (10) NULL,
[BranchGroupId] [int] NULL,
[MaxQueryLevel] [varchar] (20) NULL,
[CRMIsProcessed] [char] (1) NOT NULL,
[IPAddress] [varchar] (100) NULL,
[OTP] [varchar] (50) NULL,
[OTPTime] [datetime] NULL,
[OTPEnabled] [char] (1) NOT NULL,
[ShowDashBoard] [char] (1) NOT NULL,
[RoleIds] [varchar] (8000) NULL,
[SkipDataMasking] [varchar] (1) NULL,
[DOB] [datetime] NULL,
[CompanyState] [varchar] (100) NULL,
[Designation] [varchar] (150) NULL,
[DeletedUser] [varchar] (25) NULL,
[DeletedTime] [datetime] NOT NULL CONSTRAINT [DF__GTL_Users__Delet__60FC61CA] DEFAULT (getdate()),
[OfficialMobileNo] [varchar] (25) NULL
)
GO
ALTER TABLE [dbo].[GTL_Users_Log] ADD CONSTRAINT [PK__GTL_User__498A4454E3A4B271] PRIMARY KEY CLUSTERED ([PK_SlNo])
GO
