SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--CREATE OR ALTER PROCEDURE dbo.UpdateSpotPrice 
--	@VENUECODE	varchar(20),
--	@VENUESCRIPCODE	varchar(50),
--	@LASTTRADEDPRICE decimal(18,4),
--	@CHANGE_FLAG int
--AS
--BEGIN

--	MERGE INTO SECURITY AS t
--	USING (VALUES (@VENUECODE, @VENUESCRIPCODE, @LASTTRADEDPRICE, @CHANGE_FLAG)) AS s (VENUECODE, VENUESCRIPCODE, LASTTRADEDPRICE, CHANGE_FLAG)
--	ON t.VENUESCRIPCODE = s.VENUESCRIPCODE AND t.VENUECODE = s.VENUECODE
--	WHEN MATCHED THEN 
--		UPDATE SET t.LASTTRADEDPRICE = s.LASTTRADEDPRICE, t.CHANGE_FLAG = s.CHANGE_FLAG
--	WHEN NOT MATCHED THEN 
--		INSERT (VENUECODE, VENUESCRIPCODE, LASTTRADEDPRICE, CHANGE_FLAG) 
--		VALUES (s.VENUECODE, s.VENUESCRIPCODE, s.LASTTRADEDPRICE, s.CHANGE_FLAG);

--	--MERGE INTO SECURITY(VENUECODE,VENUESCRIPCODE,LASTTRADEDPRICE,CHANGE_FLAG,SPOT_LASTTRADEDPRICE ) 
--	--KEY(VENUESCRIPCODE,VENUECODE) 
--	--VALUES (@VENUECODE,@VENUESCRIPCODE,@LASTTRADEDPRICE,1,@SPOT_LASTTRADEDPRICE)
               

--	UPDATE SECURITY 
--	SET SPOT_LASTTRADEDPRICE = @LASTTRADEDPRICE, CHANGE_FLAG = @CHANGE_FLAG 
--	WHERE SPOT_VENUESCRIPCODE = @VENUESCRIPCODE AND SPOT_VENUECODE = @VENUECODE;

--END

--GO

--CREATE OR ALTER PROCEDURE dbo.UpdateSpotLTD 
--    @VENUECODE	varchar(20),
--	@VENUESCRIPCODE	varchar(50),
--	@LASTTRADEDPRICE decimal(18,4),
--	@SPOT_LASTTRADEDPRICE decimal(18,4),
--	@SPOT_VENUESCRIPCODE decimal(18,4),
--	@SPOT_VENUECODE varchar(20)
--AS
--BEGIN

--IF @LASTTRADEDPRICE <> 0
--BEGIN
--	IF @SPOT_LASTTRADEDPRICE <> 0
--	BEGIN
--		MERGE INTO SECURITY AS target
--		USING (VALUES (@VENUECODE, @VENUESCRIPCODE, @LASTTRADEDPRICE, 1, @SPOT_LASTTRADEDPRICE)) 
--			  AS source (VENUECODE, VENUESCRIPCODE, LASTTRADEDPRICE, CHANGE_FLAG, SPOT_LASTTRADEDPRICE)
--		ON target.VENUESCRIPCODE = source.VENUESCRIPCODE AND target.VENUECODE = source.VENUECODE
--		WHEN MATCHED THEN 
--			UPDATE SET target.LASTTRADEDPRICE = source.LASTTRADEDPRICE, 
--					   target.CHANGE_FLAG = source.CHANGE_FLAG,
--					   target.SPOT_LASTTRADEDPRICE = source.SPOT_LASTTRADEDPRICE
--		WHEN NOT MATCHED THEN 
--			INSERT (VENUECODE, VENUESCRIPCODE, LASTTRADEDPRICE, CHANGE_FLAG, SPOT_LASTTRADEDPRICE) 
--			VALUES (source.VENUECODE, source.VENUESCRIPCODE, source.LASTTRADEDPRICE, source.CHANGE_FLAG, source.SPOT_LASTTRADEDPRICE);

--		UPDATE SECURITY 
--		SET SPOT_LASTTRADEDPRICE = @SPOT_LASTTRADEDPRICE, CHANGE_FLAG = 1 
--		WHERE SPOT_VENUESCRIPCODE = @SPOT_VENUESCRIPCODE AND SPOT_VENUECODE = @SPOT_VENUECODE;
--	END
--	ELSE
--	BEGIN
--		MERGE INTO SECURITY AS target
--		USING (SELECT @VENUECODE AS VENUECODE, 
--					  @VENUESCRIPCODE AS VENUESCRIPCODE, 
--					  @LASTTRADEDPRICE AS LASTTRADEDPRICE, 
--					  1 AS CHANGE_FLAG) AS source
--		ON target.VENUESCRIPCODE = source.VENUESCRIPCODE 
--		AND target.VENUECODE = source.VENUECODE
--		WHEN MATCHED THEN 
--			UPDATE SET target.LASTTRADEDPRICE = source.LASTTRADEDPRICE, 
--					   target.CHANGE_FLAG = source.CHANGE_FLAG
--		WHEN NOT MATCHED THEN 
--			INSERT (VENUECODE, VENUESCRIPCODE, LASTTRADEDPRICE, CHANGE_FLAG) 
--			VALUES (source.VENUECODE, source.VENUESCRIPCODE, source.LASTTRADEDPRICE, source.CHANGE_FLAG);

--		UPDATE SECURITY 
--		SET CHANGE_FLAG = 1 
--		WHERE SPOT_VENUESCRIPCODE = @SPOT_VENUESCRIPCODE 
--		AND SPOT_VENUECODE = @SPOT_VENUECODE;
--	END
--END
--ELSE 
--BEGIN
--	IF @SPOT_LASTTRADEDPRICE <> 0
--	BEGIN
--		MERGE INTO SECURITY AS target
--		USING (SELECT @VENUECODE AS VENUECODE, 
--					  @VENUESCRIPCODE AS VENUESCRIPCODE, 
--					  1 AS CHANGE_FLAG, 
--					  @SPOT_LASTTRADEDPRICE AS SPOT_LASTTRADEDPRICE) AS source
--		ON target.VENUESCRIPCODE = source.VENUESCRIPCODE 
--		AND target.VENUECODE = source.VENUECODE
--		WHEN MATCHED THEN 
--			UPDATE SET target.SPOT_LASTTRADEDPRICE = source.SPOT_LASTTRADEDPRICE, 
--					   target.CHANGE_FLAG = source.CHANGE_FLAG
--		WHEN NOT MATCHED THEN 
--			INSERT (VENUECODE, VENUESCRIPCODE, CHANGE_FLAG, SPOT_LASTTRADEDPRICE) 
--			VALUES (source.VENUECODE, source.VENUESCRIPCODE, source.CHANGE_FLAG, source.SPOT_LASTTRADEDPRICE);

--		UPDATE SECURITY 
--		SET SPOT_LASTTRADEDPRICE = @SPOT_LASTTRADEDPRICE, CHANGE_FLAG = 1 
--		WHERE SPOT_VENUESCRIPCODE = @SPOT_VENUESCRIPCODE 
--		AND SPOT_VENUECODE = @SPOT_VENUECODE;

--	END
--	ELSE
--	BEGIN
--		MERGE INTO SECURITY AS target
--		USING (SELECT @VENUECODE AS VENUECODE, 
--					  @VENUESCRIPCODE AS VENUESCRIPCODE, 
--					  1 AS CHANGE_FLAG) AS source
--		ON target.VENUESCRIPCODE = source.VENUESCRIPCODE 
--		AND target.VENUECODE = source.VENUECODE
--		WHEN MATCHED THEN 
--			UPDATE SET target.CHANGE_FLAG = source.CHANGE_FLAG
--		WHEN NOT MATCHED THEN 
--			INSERT (VENUECODE, VENUESCRIPCODE, CHANGE_FLAG, SPOT_LASTTRADEDPRICE) 
--			VALUES (source.VENUECODE, source.VENUESCRIPCODE, source.CHANGE_FLAG);

--		UPDATE SECURITY 
--		SET CHANGE_FLAG = 1 
--		WHERE SPOT_VENUESCRIPCODE = @SPOT_VENUESCRIPCODE 
--		AND SPOT_VENUECODE = @SPOT_VENUECODE;
--	END

--END

--END

--GO

--exec UpdateClientDetailsDynamically '100','90','mgn','200','mgnrate','67','dat','55','plv083'
CREATE   PROCEDURE [dbo].[UpdateClientDetailsDynamically] 
	@ADDMGN decimal(20,4),	
	@SPANMGN decimal(20,4), 
    @cln1 VARCHAR(100),
    @cln1Data DECIMAL(18,4),
	@cln2 VARCHAR(100),
    @cln2Data DECIMAL(18,4),
	@cln3 VARCHAR(100),
    @cln3Data DECIMAL(18,4), 
    @usercode VARCHAR(30),
	@IsLoadMargin varchar(2)
AS
BEGIN
SET NOCOUNT ON
	insert into rmstestlog(spname,remarks)
	values('UpdateClientDetailsDynamically','start')

    DECLARE @sql NVARCHAR(MAX);--,@ADDMGN decimal(20,4),@SPANMGN decimal(20,4);

	IF @IsLoadMargin ='T'
		SELECT @ADDMGN = ISNULL(ADDMGNBOOKED,0),@SPANMGN = ISNULL(SPANMARGIN,0) from USERACCOUNT WITH (NOLOCK) WHERE USERCODE=@usercode;

	SET @sql = N'UPDATE CLIENTDETAILS SET ADDMGN = @ADDMGN,SPANMGN = @SPANMGN, ' + QUOTENAME(@cln1) + ' = @cln1Data ,' + QUOTENAME(@cln2) + ' = @cln2Data ,' +
	 QUOTENAME(@cln3) + ' = @cln3Data '+' WHERE usercode = @usercode;';

    EXEC sp_executesql @sql,  
    N'@ADDMGN DECIMAL(18,4),  
      @SPANMGN DECIMAL(18,4),  
      @cln1Data DECIMAL(18,4),
      @cln2Data DECIMAL(18,4),  
      @cln3Data DECIMAL(18,4), 
      @usercode VARCHAR(30)',  
    @ADDMGN,  
    @SPANMGN,  
    @cln1Data,  
    @cln2Data,  
    @cln3Data,  
    @usercode;
	--SET @sql = 'UPDATE testrms SET ADDMGN =' +@ADDMGN+',SPANMGN = '+@SPANMGN +', ' +@cln1+ ' = '+@cln1Data+' ,' +@cln2 + ' = '+@cln2Data+' ,' +
	-- @cln3 + ' = '+@cln3Data+' WHERE usercode = @usercode;';

	--exec @sql
	--PRINT @sql; 
END;


GO
