SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--CREATE OR ALTER PROCEDURE dbo.UpdateSecLTD 
--    @LASTTRADEDPRICE datetime,
--	@CLOSEDPRICE decimal(18,4),
--	@CHANGE_FLAG int,
--	@VENUECODE varchar(30),
--	@VENUESCRIPCODE varchar(40)
--AS
--BEGIN
	
--UPDATE SECURITY SET LASTTRADEDPRICE=@LASTTRADEDPRICE,CLOSEDPRICE=@CLOSEDPRICE,CHANGE_FLAG=@CHANGE_FLAG 
--	WHERE VENUECODE=@VENUECODE AND VENUESCRIPCODE=@VENUESCRIPCODE;	

--END

--GO

--CREATE OR ALTER PROCEDURE dbo.GetVenuecodes 
--AS
--BEGIN
--SET NOCOUNT ON
--	select distinct(venuecode) from security(nolock);
--END

--GO
CREATE   PROCEDURE [dbo].[GetVenuecodes]
AS 
BEGIN
	select distinct(venuecode),Security,SECtyp from security(nolock);

END
GO
