SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROC [dbo].[InsertToPortfoliotemp]
(
	@USERCODE varchar(30),
	@VENUECODE	varchar(20),
	@VENUESCRIPCODE	varchar(50),
	@SECURITYCODE varchar(100),
	@SERIES	varchar(50),
	@ISIN varchar(12),
	@INSTRUMENTTYPE	varchar(20),
	@STRIKEPRICE decimal(20,4),
	@CALLPUT varchar(1),	     	     
	@STYLE varchar(1),	     	     
	@PREVIOUSBOUGHTQTY decimal(20,4),    
	@BOUGHTQTY decimal(20,4),  
	@SOLDQTY decimal(20,4),  --
	@PENDINGBOUGHTQTY decimal(20,4),   
	@PENDINGSOLDQTY decimal(20,4),
	@TOTALQTY decimal(20,4)=0,
	@PORTFOLIOTYPE int,
	@BUYVAL decimal(20,4),
	@SELLVAL decimal(20,4),
	@BPBOOKED decimal(20,4),
	@PENDINGBUYVAL decimal(20,4),
	@PENDINGSELLVAL decimal(20,4),
	@PREVIOUSSOLDQTY decimal(20,4),
	@PREVIOUSBOUGHTVAL decimal(20,4),
	@PREVIOUSSOLDVAL decimal(20,4),
	@UNITS decimal(20,4),
	@PREVIOUSBPBOOKED decimal(20,4),
	@BOOKEDPANDL decimal(20,4),
	@SOLDFROMHOLDING decimal(20,4),
	@OPENBUYQTY decimal(20,4),
	@OPENBUYVAL decimal(20,4),
	@OPENSELLQTY decimal(20,4),
	@OPENSELLVAL decimal(20,4),
	@UNREALPANDL decimal(20,4)=0,
	@OPENVAL decimal(20,4),
	@OPENQTY decimal(20,4),
	@SEGMENT int,
	@CONVERTEDBUYQTY decimal(20,4),
	@CONVERTEDSELLQTY decimal(20,4),
	@CONVERTEDBUYVAL decimal(20,4),
	@CONVERTEDSELLVAL decimal(20,4),
	@RECEIVEDBUYQTY decimal(20,4),
	@RECEIVEDSELLQTY decimal(20,4),
	@RECEIVEDBUYVAL decimal(20,4),
	@RECEIVEDSELLVAL decimal(20,4),
	@UNSETTLEDQTY decimal(20,4),
	@NBUYQTY decimal(20,4),
	@NSELLQTY decimal(20,4),
	@NBUYVALUE decimal(20,4),
	@NSELLVALUE decimal(20,4),
	@PREMIUMBOOKED decimal(20,4),
	@DPQTY decimal(20,4),
	@BLOCKEDQTY decimal(20,4),
	@ORDERSEQNO decimal(20,4),
	@RISKMANAGEMENT int,
	@BROKERAGEBOOKED decimal(20,4),
	@TRANSID decimal(20,4)=0,
	@AVGRATE decimal(20,4)=0,
	@PREVIOUSCONVERTEDBUYQTY decimal(20,5),
	@PREVIOUSCONVERTEDSELLQTY decimal(20,5),
	@PREVIOUSCONVERTEDBUYVAL decimal(20,5),
	@PREVIOUSCONVERTEDSELLVAL decimal(20,5),
	@EXPIRATIONDATE DATETIME,
	@PLEDGEQTY decimal(20,4),
	@PLEDGEQTYRECOVERED decimal(18,4)=0

)AS
/*
	EXEC InsertToPortfoliotemp 'PLV083','NSEFO',35001,'NIFTY','','','FUTIDX',0.0,'X','X',0.0,0.0,975.0,0.0,975.0,0.0,1,0.0,2.24317275E7,0.0,0.0,2.24317275E7,
	0.0,0.0,0.0,1.0,0.0,0.0,1950.0,0.0,0.0,975.0,2.24317275E7,0.0,2.24317275E7,-975.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,975.0,0.0,2.24317275E7,
	0.0,0.0,0.0,268704.0,1,0.0,2.1186847E7,0.0,0.0,0.0,0.0,0.0,'2025-03-27 00:00:00.0',0.0,0.0
*/
BEGIN
SET NOCOUNT ON;
	
	DECLARE @LASTTRADEDPRICE decimal(20,4);
	SELECT @LASTTRADEDPRICE= LASTTRADEDPRICE FROM SECURITY(NOLOCK) WHERE VENUECODE=@VENUECODE and VENUESCRIPCODE=@VENUESCRIPCODE

	INSERT INTO portfoliotemp(USERCODE,VENUECODE,VENUESCRIPCODE,SECURITYCODE,SERIES,ISIN,
		INSTRUMENTTYPE,STRIKEPRICE,CALLPUT,STYLE,PREVIOUSBOUGHTQTY,BOUGHTQTY,SOLDQTY,PENDINGBOUGHTQTY,PENDINGSOLDQTY,
		LASTUPDATEDON,TOTALQTY,PORTFOLIOTYPE,BUYVAL,SELLVAL,BPBOOKED,PENDINGBUYVAL,PENDINGSELLVAL,PREVIOUSSOLDQTY,PREVIOUSBOUGHTVAL,PREVIOUSSOLDVAL,
		UNITS,PREVIOUSBPBOOKED,BOOKEDPANDL,SOLDFROMHOLDING,OPENBUYQTY,OPENBUYVAL,OPENSELLQTY,
		OPENSELLVAL,UNREALPANDL,OPENVAL,OPENQTY,CHANGE_FLAG,SEGMENT,CONVERTEDBUYQTY, CONVERTEDSELLQTY, CONVERTEDBUYVAL,
		CONVERTEDSELLVAL, RECEIVEDBUYQTY, RECEIVEDSELLQTY, RECEIVEDBUYVAL, RECEIVEDSELLVAL,UNSETTLEDQTY,NBUYQTY,NSELLQTY,NBUYVALUE,NSELLVALUE,PREMIUMBOOKED,
		DPQTY,BLOCKEDQTY,MRKTRATE,PORTFOLIOLOADED,ORDERSEQNO,RISKMANAGEMENT,BROKERAGEBOOKED,PREVBOUGHTAVGRATE,TRANSID,AVGRATE,DBFLAG,TEMPFLAG,
		PREVIOUSCONVERTEDBUYQTY,PREVIOUSCONVERTEDSELLQTY,PREVIOUSCONVERTEDBUYVAL,PREVIOUSCONVERTEDSELLVAL,EXPIRATIONDATE,PLEDGEQTY,PLEDGEQTYRECOVERED)
	VALUES(@USERCODE ,@VENUECODE,@VENUESCRIPCODE,@SECURITYCODE,@SERIES,@ISIN,
		@INSTRUMENTTYPE,@STRIKEPRICE,@CALLPUT,@STYLE,@PREVIOUSBOUGHTQTY,@BOUGHTQTY,@SOLDQTY,@PENDINGBOUGHTQTY,@PENDINGSOLDQTY,
		getdate(),@TOTALQTY,@PORTFOLIOTYPE,@BUYVAL,@SELLVAL,@BPBOOKED,@PENDINGBUYVAL,@PENDINGSELLVAL,@PREVIOUSSOLDQTY,@PREVIOUSBOUGHTVAL,@PREVIOUSSOLDVAL ,
		@UNITS,@PREVIOUSBPBOOKED,@BOOKEDPANDL,@SOLDFROMHOLDING,@OPENBUYQTY,@OPENBUYVAL,@OPENSELLQTY,
		@OPENSELLVAL,@UNREALPANDL,@OPENVAL,@OPENQTY,1,@SEGMENT,@CONVERTEDBUYQTY,@CONVERTEDSELLQTY,@CONVERTEDBUYVAL,
		@CONVERTEDSELLVAL,@RECEIVEDBUYQTY,@RECEIVEDSELLQTY,@RECEIVEDBUYVAL,@RECEIVEDSELLVAL,@UNSETTLEDQTY,@NBUYQTY,@NSELLQTY,@NBUYVALUE,@NSELLVALUE,@PREMIUMBOOKED,
		@DPQTY,@BLOCKEDQTY,@LASTTRADEDPRICE,1,@ORDERSEQNO,@RISKMANAGEMENT,@BROKERAGEBOOKED,@LASTTRADEDPRICE,@TRANSID,@AVGRATE,1,1,
		@PREVIOUSCONVERTEDBUYQTY,@PREVIOUSCONVERTEDSELLQTY,@PREVIOUSCONVERTEDBUYVAL,@PREVIOUSCONVERTEDSELLVAL,@EXPIRATIONDATE ,@PLEDGEQTY,@PLEDGEQTYRECOVERED)

END
GO
