SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[UpdateSquareOffEnable] 
    @SQUAREOFFENABLE varchar(20),
	@BLOCKSOURCE varchar(50),
	@USERCODE varchar(30),
	@BLOCKFLAG int
AS
/*
 exec UpdateSquareOffEnable
*/
BEGIN
	IF @BLOCKFLAG = 1
	BEGIN
		UPDATE clientdetails SET SQUAREOFFENABLE=@SQUAREOFFENABLE,BLOCKSOURCE=@BLOCKSOURCE 
		WHERE USERCODE=@USERCODE and BLOCKSOURCE <> 'PD' and BLOCKSOURCE <> 'ID'
	END
	ELSE IF @BLOCKFLAG = 0
	BEGIN
		UPDATE clientdetails SET SQUAREOFFENABLE=@SQUAREOFFENABLE,BLOCKSOURCE=@BLOCKSOURCE 
		WHERE USERCODE=@USERCODE and BLOCKSOURCE <> 'CRD'
	END
END
	 
GO
