SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[InsertToClientmargin] 
    @USERCODE varchar(20)
	--@REGION varchar(20),
	--@LOCATION varchar(20),
	--@CLIENTTYPE varchar(20),
	--@BOCLIENTTYPE varchar(20),
	--@LEDGER decimal(20,4),
	--@RTHOLDINGVAL decimal(20,4),
	--@PREMIUM decimal(20,4),
	--@MARGINREQ decimal(20,4),
	--@RTDEBIT decimal(20,4),
	--@RTPOSITION decimal(20,4),
	--@FOMVPER decimal(20,4),
	--@TOTALMVPER decimal(20,4),
	--@CASHMTM decimal(20,4),
	--@FOMTM decimal(20,4),
	--@TOTALMTM decimal(20,4),
	--@TOTALBOOKEDPANDL decimal(20,4),
	--@ASSIGNMENTVALUE decimal(20,4),
	--@CALCFLAG int,
	--@PLEDGEPOSITION decimal(20,4),
	--@SHORTMRKTVAL decimal(20,4),
	--@PENDINGJOURNAL decimal(15,3),
	--@OPTMRKTVAL decimal(20,4),
	--@MFINTRADAYHOLDVAL decimal(20,4),
	--@FIXEDBALANCE decimal(20,4),	
	--@REDUCEDBP decimal(20,4),
	--@EXGLATEDELIVERYVALUE decimal(20,5),
	--@BANKGARANTEE decimal(20,4),
	--@DPPOSITION decimal(20,4),
	--@UNSETTLEDPOSITION decimal(20,4)
AS
BEGIN
SET NOCOUNT ON
	insert into rmstestlog(spname,remarks)
	values('InsertToClientmargin','start')
	INSERT INTO FLIP.dbo.CLIENTMARGIN(USERCODE,REGION,LOCATION,CLIENTTYPE,BOCLIENTTYPE,LEDGER,LEDGERFORMTM,RTHOLDINGVAL,PREMIUM,MARGINREQ,RTDEBIT,RTPOSITION,TOTALMVPER,TOTALMTMPER,NEWTOTALMTM,
		TODAYSMTM,TOTALMTM,NOTIONALLEDGER,TOTALCOLLATRAL,NVVALUE,RTCOLLATERAL,TOTALBOOKEDPANDL,ASSIGNMENTVALUE,OPTCOVERVAL,SHORTMRKTVAL,PENDINGJOURNAL,OPTMRKTVAL,MFINTRADAYHOLDVAL,FIXEDBALANCE,BATCHNO,EXGLATEDELIVERYVALUE,
		BANKGARANTEE,DPPOSITION,UNSETTLEDPOSITION,PLEDGEPOSITION,SQUAREOFFENABLE,MTF_BALANCE,RISKMANAGEMENT,ACTUALHOLDINGVALUE,BROKERAGEBOOKED,SHORTSELLVALUE,HOLDSELLVAL,JOINEDDPAC,BTST_BALANCE,MTFCOLLACTERAL,PREVBUYVAL,
		PREVBUYVALOPEN,PREVHOLDSELLLVAL,MTFSTOCKVAL,MTFMGN,MTFLEDGER,BANKWITHDRAW,BANKDEPOSIT,DPHOLDSELLLVAL,TOTALPREMIUMBOOKED,PREVOPTIONMKTVAL,PREVOPTIONMKTVALOPEN,PREVOPTIONSELLVAL,TOTALSPANMGN,TOTALADDMGN,REMARKS,
		LEDGER_BALANCE,BOOKEDPANDLFOR_MTM,LASTUPDATEDON,FOMTM,CASHMTM)
	select USERCODE,REGION,LOCATION,CLIENTTYPE,BOCLIENTTYPE,LEDGER,LEDGERFORMTM,RTHOLDINGVAL,PREMIUM,MARGINREQ,RTDEBIT,RTPOSITION,TOTALMVPER,TOTALMTMPER,NEWTOTALMTM,
		TODAYSMTM,TOTALMTM,NOTIONALLEDGER,TOTALCOLLATRAL,NVVALUE,RTCOLLATERAL,TOTALBOOKEDPANDL,ASSIGNMENTVALUE,OPTCOVERVAL,SHORTMRKTVAL,PENDINGJOURNAL,OPTMRKTVAL,MFINTRADAYHOLDVAL,FIXEDBALANCE,BATCHNO,EXGLATEDELIVERYVALUE,
		BANKGARANTEE,DPPOSITION,UNSETTLEDPOSITION,PLEDGEPOSITION,SQUAREOFFENABLE,MTF_BALANCE,RISKMANAGEMENT,ACTUALHOLDINGVALUE,BROKERAGEBOOKED,SHORTSELLVALUE,HOLDSELLVAL,JOINEDDPAC,BTST_BALANCE,MTFCOLLACTERAL,PREVBUYVAL,
		PREVBUYVALOPEN,PREVHOLDSELLLVAL,MTFSTOCKVAL,MTFMGN,MTFLEDGER,BANKWITHDRAW,BANKDEPOSIT,DPHOLDSELLLVAL,TOTALPREMIUMBOOKED,PREVOPTIONMKTVAL,PREVOPTIONMKTVALOPEN,PREVOPTIONSELLVAL,TOTALSPANMGN,TOTALADDMGN,REMARKS,
		LEDGER_BALANCE,BOOKEDPANDLFOR_MTM,LASTUPDATEDON,FOMTM,CASHMTM 
	from clientmargin(nolock) where usercode=@UserCode

	--Insert INTO clientmargin(USERCODE,REGION,LOCATION,CLIENTTYPE,BOCLIENTTYPE,LEDGER,RTHOLDINGVAL,PREMIUM,MARGINREQ,RTDEBIT,RTPOSITION,FOMVPER,
	--	TOTALMVPER,CASHMTM,FOMTM,TOTALMTM,TOTALBOOKEDPANDL,ASSIGNMENTVALUE,CALCFLAG,PLEDGEPOSITION,SHORTMRKTVAL,PENDINGJOURNAL,OPTMRKTVAL,MFINTRADAYHOLDVAL,
	--	FIXEDBALANCE,REDUCEDBP,EXGLATEDELIVERYVALUE,BANKGARANTEE,DPPOSITION,UNSETTLEDPOSITION,CALMARGINTIME)
 --   VALUES (@USERCODE,@REGION,@LOCATION,@CLIENTTYPE,@BOCLIENTTYPE,@LEDGER,@RTHOLDINGVAL,@PREMIUM,@MARGINREQ,@RTDEBIT,@RTPOSITION,@FOMVPER,
	--	@TOTALMVPER,@CASHMTM,@FOMTM,@TOTALMTM,@TOTALBOOKEDPANDL,@ASSIGNMENTVALUE,@CALCFLAG,@PLEDGEPOSITION,@SHORTMRKTVAL,@PENDINGJOURNAL,@OPTMRKTVAL,@MFINTRADAYHOLDVAL,
	--	@FIXEDBALANCE,@REDUCEDBP,@EXGLATEDELIVERYVALUE,@BANKGARANTEE,@DPPOSITION,@UNSETTLEDPOSITION,GETDATE())

END

GO
