SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--CREATE OR ALTER PROCEDURE dbo.insertToClientdetails 
--    @USERCODE varchar(20), 
--	@CLIENTTYPE varchar(20), 
--	@BOCLIENTTYPE varchar(20), 
--	@LOCATION varchar(20), 
--	@TRADEFLAG int, 
--	@PENDINGJOURNAL decimal(20,4), 
--	@MTF_BALANCE decimal(20,4), 
--	@LEDGER decimal(20,4), 
--	@BANKDEPOSIT decimal(20,4), 
--	@BANKWITHDRAW decimal(20,4), 
--	@POAFLAG varchar(2), 
--	@REGION varchar(20), 
--	@Joineddpac  varchar(10), 
--	@SQUAREOFFENABLE int, 
--	@BLOCKSOURCE  varchar(20), 
--	@PORTFOLIOLOADED int, 
--	@CREDITLIMIT decimal(20,4), 
--	@CREDITAPPROVED decimal(20,4), 
--	@CREDITPERUSED decimal(20,4), 
--	@MTFLEDGER decimal(20,4), 
--	@BTST_BALANCE decimal(20,4),
--	@FIXEDBALANCE decimal(20,4),
--	@EXGLATEDELIVERYVALUE decimal(20,4),
--	@BANKGARANTEE decimal(20,4),
--	@ADDMGN decimal(20,4),
--	@SPANMGN decimal(20,4),
--	@ADDMGN_NCDEX decimal(20,4),
--	@SPANMARGIN_NCDEX decimal(20,4),
--	@ADDMGN_MCX decimal(20,4),
--	@SPANMARGIN_MCX decimal(20,4),
--	@ADDMGN_NSECOM decimal(20,4),
--	@SPANMARGIN_NSECOM decimal(20,4),
--	@ADDMGN_NSECD decimal(20,4),
--	@SPANMARGIN_NSECD decimal(20,4),
--	@ADDMGN_NSEFO decimal(20,4),
--	@SPANMARGIN_NSEFO decimal(20,4),
--	@ADDMGN_NCDEX_INTRADAY decimal(20,4),
--	@ADDMGN_MCX_INTRADAY decimal(20,4),
--	@ADDMGN_NSEFO_INTRADAY decimal(20,4),
--	@ADDMGN_NSECD_INTRADAY decimal(20,4),
--	@NotPostedSauda decimal(20,4),
--	@MTMProfit decimal(20,4),
--	@MTF_BALANCEONLY decimal(18,6),
--	@CashLedgerOnly decimal(18,6),
--	@FOLedger decimal(18,6),
--	@NotPostedSauda_2 decimal(18,6),
--	@DebitPenalty decimal(18,6),
--	@AllSpan decimal(18,6),
--	@BTSTValue decimal(18,6),
--	@IPOOffline decimal(18,6),
--	@FOMTMForCashSegment decimal(18,6),
--	@EPI_Value decimal(20,4),
--	@ADDITIONALVALUES varchar(1000),
--	@MTF_Unac_Interest  decimal(18,6)
--AS
--BEGIN
--SET NOCOUNT ON

--	insert into rmstestlog(spname,remarks)
--	values('insertToClientdetails','start')

--	INSERT INTO CLIENTDETAILS (USERCODE, CLIENTTYPE, BOCLIENTTYPE, LOCATION, TRADEFLAG, PENDINGJOURNAL, MTF_BALANCE, LEDGER, BANKDEPOSIT, 
--	BANKWITHDRAW, POAFLAG, REGION, Joineddpac, SQUAREOFFENABLE, BLOCKSOURCE, PORTFOLIOLOADED, CREDITLIMIT, CREDITAPPROVED, CREDITPERUSED, 
--	MTFLEDGER, BTST_BALANCE,FIXEDBALANCE,EXGLATEDELIVERYVALUE,BANKGARANTEE,ADDMGN,SPANMGN,ADDMGN_NCDEX,SPANMARGIN_NCDEX,ADDMGN_MCX,SPANMARGIN_MCX,
--	ADDMGN_NSECOM,SPANMARGIN_NSECOM,ADDMGN_NSECD,SPANMARGIN_NSECD,ADDMGN_NSEFO,SPANMARGIN_NSEFO,ADDMGN_NCDEX_INTRADAY,ADDMGN_MCX_INTRADAY,
--	ADDMGN_NSEFO_INTRADAY,ADDMGN_NSECD_INTRADAY,NotPostedSauda,MTMProfit,MTF_BALANCEONLY,CashLedgerOnly,FOLedger,NotPostedSauda_2,DebitPenalty,
--	AllSpan,BTSTValue,IPOOffline,FOMTMForCashSegment,EPI_Value,ADDITIONALVALUES,MTF_Unac_Interest)
--	VALUES(@USERCODE, @CLIENTTYPE, @BOCLIENTTYPE, @LOCATION, @TRADEFLAG, @PENDINGJOURNAL, @MTF_BALANCE, @LEDGER, @BANKDEPOSIT, 
--	@BANKWITHDRAW, @POAFLAG, @REGION, @Joineddpac, @SQUAREOFFENABLE, @BLOCKSOURCE, @PORTFOLIOLOADED, @CREDITLIMIT, @CREDITAPPROVED, @CREDITPERUSED, 
--	@MTFLEDGER, @BTST_BALANCE,@FIXEDBALANCE,@EXGLATEDELIVERYVALUE,@BANKGARANTEE,@ADDMGN,@SPANMGN,@ADDMGN_NCDEX,@SPANMARGIN_NCDEX,@ADDMGN_MCX,@SPANMARGIN_MCX,
--	@ADDMGN_NSECOM,@SPANMARGIN_NSECOM,@ADDMGN_NSECD,@SPANMARGIN_NSECD,@ADDMGN_NSEFO,@SPANMARGIN_NSEFO,@ADDMGN_NCDEX_INTRADAY,@ADDMGN_MCX_INTRADAY,
--	@ADDMGN_NSEFO_INTRADAY,@ADDMGN_NSECD_INTRADAY,@NotPostedSauda,@MTMProfit,@MTF_BALANCEONLY,@CashLedgerOnly,@FOLedger,@NotPostedSauda_2,@DebitPenalty,
--	@AllSpan,@BTSTValue,@IPOOffline,@FOMTMForCashSegment,@EPI_Value,@ADDITIONALVALUES,@MTF_Unac_Interest)

--END

--GO

--CREATE OR ALTER PROCEDURE dbo.deleteFromSquareoff 
--    @usercode varchar(30) ='' 
--AS
--BEGIN
--SET NOCOUNT ON  
--	IF @usercode<>''
--		DELETE FROM SQUAREOFFPORTFOLIO where usercode=@usercode
--	ELSE
--		DELETE FROM SQUAREOFFPORTFOLIO 
--END

--GO

CREATE   PROCEDURE [dbo].[UpdatePortfolioClientType] 
AS
BEGIN
SET NOCOUNT ON  
	
	--DECLARE @clienttype varchar(20),
	--@usercode  varchar(20);

	--SELECT @usercode=p1.USERCODE ,@clienttype=Max(p1.ClIENTTYPE)  
	--FROM CLIENTDETAILS(nolock) p1 INNER JOIN PORTFOLIO(nolock) P2 
	--ON p1.USERCODE=P2.USERCODE WHERE p2.clIENTTYPE  IS NULL
	--GROUP BY p1.USERCODE;

	--UPDATE PORTFOLIO SET CLIENTTYPE=@clienttype WHERE USERCODE = @usercode;
	insert into rmstestlog(spname,remarks)
	values('UpdatePortfolioClientType','start')

	UPDATE p2
	SET CLIENTTYPE = p1.ClientType
	FROM PORTFOLIO p2
	INNER JOIN (
		SELECT p1.USERCODE, MAX(p1.ClIENTTYPE) AS ClientType
		FROM CLIENTDETAILS p1
		GROUP BY p1.USERCODE
	) p1 ON p2.USERCODE = p1.USERCODE
	WHERE p2.CLIENTTYPE IS NULL;

END

GO
