SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[getPortfolioDetails] 
    @orderingUserCode varchar(30),
	@venueCode varchar(30)='',
	@securityCode varchar(100)='',
	@productType int =0,
	@segment int =0,
	@IsQty varchar(2)='N'

AS
/*
	exec getPortfolioDetails 'plv083','','',0,0,'Y'
*/
BEGIN
SET NOCOUNT ON

	IF @IsQty='N'
	BEGIN
	insert into rmstestlog(spname,remarks)
	values('getPortfolioDetails','start -N')

		SELECT USERCODE,BATCHNO,VENUECODE ,VENUESCRIPCODE,SECURITYCODE,INSTRUMENTTYPE , SERIES,EXPIRATIONDATE,STYLE, CALLPUT ,STRIKEPRICE ,
			PORTFOLIOTYPE,BOUGHTQTY,SOLDQTY ,MRKTRATE ,BUYVAL ,SELLVAL ,MTMFORMV,NEWTOTALMTM ,OPENQTY ,MRKTVAL ,DPQTY,UNSETTLEDQTY,PREVBOUGHTAVGRATE ,AVGRATE,
			ISIN,PENDINGBOUGHTQTY,PENDINGSOLDQTY,BPBOOKED,PENDINGBUYVAL,PENDINGSELLVAL,UNITS,BOOKEDPANDL,HOLDINGVAL,SOLDFROMHOLDING,OPENBUYQTY,OPENBUYVAL,OPENSELLQTY,OPENSELLVAL,OPENVAL,SEGMENT,
			PREMIUMBOOKED,PREVIOUSBPBOOKED,PREVIOUSBOUGHTQTY,PREVIOUSSOLDQTY,PREVIOUSBOUGHTVAL,PREVIOUSSOLDVAL,CONVERTEDBUYQTY,CONVERTEDSELLQTY,CONVERTEDBUYVAL,CONVERTEDSELLVAL,RECEIVEDBUYQTY,
			RECEIVEDSELLQTY,RECEIVEDBUYVAL,RECEIVEDSELLVAL,NBUYQTY,NSELLQTY,NBUYVALUE,NSELLVALUE,PREVPREMIUMBOOKED,PLEDGEQTY,BLOCKEDQTY,RISKMANAGEMENT,BROKERAGEBOOKED,PREVBOUGHTVALWITHCLOSINGRATE,AVGFROMCLOSING,MTFMGNPER,CLOSEDPRICE,TODAYSMTM
		 FROM PORTFOLIO(NOLOCK) WHERE USERCODE=@orderingUserCode;
	END
	ELSE
	BEGIN
	insert into rmstestlog(spname,remarks)
	values('getPortfolioDetails','start - Y')

		DECLARE @sql NVARCHAR(MAX);  

		SET @sql = N'  
			SELECT VenueCode, VENUESCRIPCODE, SecurityCode, InstrumentType, SERIES, EXPIRATIONDATE, Style, CallPut, StrikePrice,
				   PortfolioType, BOUGHTQTY, SOLDQTY, MRKTRATE, BuyVal, SellVal, mtmformv, newtotalmtm,
				   ((PREVIOUSBOUGHTQTY - ISNULL(PREVIOUSCONVERTEDBUYQTY,0)) + (BOUGHTQTY + RECEIVEDBUYQTY - CONVERTEDBUYQTY)
					- (PREVIOUSSOLDQTY - ISNULL(PREVIOUSCONVERTEDSELLQTY,0)) - (SOLDQTY + RECEIVEDSELLQTY - CONVERTEDSELLQTY)) AS openqty,
				   MRKTVAL, DPQty, UNSETTLEDQTY, PREVBOUGHTAVGRATE, AVGRATE
			FROM PORTFOLIO
			WHERE USERCODE = @orderingUserCodeParam ';  

		IF @venueCode <> ''
		BEGIN
			SET @sql += N'AND VENUECODE = @venueCodeParam ';  
		END;

		IF @securityCode <> ''
		BEGIN
			SET @sql += N'AND SECURITYCODE = @securityCodeParam ';  
		END;

		IF @productType <> 0
		BEGIN
			SET @sql += N'AND PORTFOLIOTYPE = @productTypeParam '; 
		END;

		IF @segment <> 0
		BEGIN
			SET @sql += N'AND SEGMENT = @segmentParam '; 
		END;

		SET @sql += N'ORDER BY RISKMANAGEMENT DESC, VENUECODE DESC';

		EXEC sp_executesql @sql, 
			N'@orderingUserCodeParam VARCHAR(30), @venueCodeParam VARCHAR(20), @securityCodeParam VARCHAR(20), @productTypeParam INT, @segmentParam INT',
			@orderingUserCodeParam = @orderingUserCode, @venueCodeParam = @venueCode, @securityCodeParam = @securityCode, @productTypeParam = @productType, @segmentParam = @segment;
	END
END

GO
