SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[GetLtd] 
    @VENUECODE	varchar(20),
	@VENUESCRIPCODE	varchar(50)
AS
BEGIN
SET NOCOUNT ON
	insert into rmstestlog(spname,remarks)
	values('GetLtd','start')

	SELECT LASTTRADEDPRICE FROM SECURITY(NOLOCK) WHERE VENUECODE = @VENUECODE  AND VENUESCRIPCODE = @VENUESCRIPCODE;
END

GO
