SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[InsertToSqroffrequesttable] 
    @USERCODE VARCHAR(30),
	@PORTFOLIOTYPE INT,
	@VENUECODE VARCHAR(30),
	@VENUESCRIPCODE VARCHAR(50),
	@QTY DECIMAL(20,4),
	@LOGINUSER VARCHAR(20)
AS
BEGIN
SET NOCOUNT ON
insert into rmstestlog(spname,remarks)
	values('InsertToSqroffrequesttable','start')
	INSERT INTO SQROFFREQUESTTABLE(USERCODE,PORTFOLIOTYPE,VENUECODE,VENUESCRIPCODE,QTY,LOGINUSER,REQUESTTIME) 
	VALUES(@USERCODE,@PORTFOLIOTYPE,@VENUECODE,@VENUESCRIPCODE,@QTY,@LOGINUSER,GETDATE())
	
END
GO
