SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[InsertToSecurityRatetemp] 
    @LASTTRADEDPRICE Decimal(18,6),
	@CHANGE_FLAG int,
	@SUBSCRIPTION_FLAG int,
	@LASTTUPDTIME varchar(50),
	@BATCHNO int,
	@RMSUPDTIME varchar(50),
	@SPOT_LASTTRADEDPRICE Decimal(20,4),
	@VENUECODE varchar(30),
	@VENUESCRIPCODE varchar(40),
	@isNSEMF Varchar(10)
	
AS
/*
exec InsertToSecurityRatetemp 100.0,1,1,'2025-02-17 10:00:10.510',1,'2025-02-17 10:00:10.510',100.0,'NSE','100087','T'
*/
BEGIN
SET NOCOUNT ON	
	IF @isNSEMF = 'T'
	begin
			insert into rmstestlog(spname,remarks)
		values('InsertToSecurityRatetemp','start')
		INSERT INTO SECURITY_RATETEMP (LASTTRADEDPRICE,CHANGE_FLAG,SUBSCRIPTION_FLAG,LASTTUPDTIME,BATCHNO,RMSUPDTIME,VENUECODE,VENUESCRIPCODE)
			VALUES(@LASTTRADEDPRICE,@CHANGE_FLAG,@SUBSCRIPTION_FLAG,cast(@LASTTUPDTIME as datetime),@BATCHNO,cast(@RMSUPDTIME as datetime),@VENUECODE,@VENUESCRIPCODE);
		if @@ROWCOUNT <>0
		insert into rmstestlog(spname,remarks)
		values('InsertToSecurityRatetemp','success')

	end
	ELSE 
	BEGIN
			insert into rmstestlog(spname,remarks)
		values('InsertToSecurityRatetemp','start')
		IF @LASTTRADEDPRICE > 0
		BEGIN
			IF @SPOT_LASTTRADEDPRICE <> 0
				INSERT INTO SECURITY_RATETEMP (LASTTRADEDPRICE,CHANGE_FLAG,SUBSCRIPTION_FLAG,LASTTUPDTIME,BATCHNO,RMSUPDTIME,SPOT_LASTTRADEDPRICE,VENUECODE,VENUESCRIPCODE)
					VALUES(@LASTTRADEDPRICE,@CHANGE_FLAG,@SUBSCRIPTION_FLAG,cast(@LASTTUPDTIME as datetime),@BATCHNO,cast(@RMSUPDTIME as datetime),@SPOT_LASTTRADEDPRICE,@VENUECODE,@VENUESCRIPCODE);
			ELSE
				INSERT INTO SECURITY_RATETEMP (LASTTRADEDPRICE,CHANGE_FLAG,SUBSCRIPTION_FLAG,LASTTUPDTIME,BATCHNO,RMSUPDTIME,VENUECODE,VENUESCRIPCODE)
					VALUES(@LASTTRADEDPRICE,@CHANGE_FLAG,@SUBSCRIPTION_FLAG,cast(@LASTTUPDTIME as datetime),@BATCHNO,cast(@RMSUPDTIME as datetime),@VENUECODE,@VENUESCRIPCODE);
		END
		ELSE IF @SPOT_LASTTRADEDPRICE <> 0
			INSERT INTO SECURITY_RATETEMP (CHANGE_FLAG,SUBSCRIPTION_FLAG,SPOT_LASTTRADEDPRICE,VENUECODE,VENUESCRIPCODE)
				VALUES(1,1,@SPOT_LASTTRADEDPRICE,@VENUECODE,@VENUESCRIPCODE);
	END
	

END

GO
