SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--CREATE OR ALTER PROCEDURE dbo.GetLttDiff
--	@SecurityTimeDiff int
--AS
--/*
--	exec GetVenuecodes '200' 
--*/
--BEGIN
--SET NOCOUNT ON;
--	WITH VenueDiff AS (
--		SELECT 
--			VENUECODE,
--			MAX(RMSUPDTIME) AS MaxRMSUPDTIME
--		FROM SECURITY
--		GROUP BY VENUECODE
--	)
--	SELECT S.VENUECODE, S.VENUESCRIPCODE
--	FROM SECURITY S
--	JOIN VenueDiff V ON S.VENUECODE = V.VENUECODE
--	WHERE S.SUBSCRIPTION_FLAG = 1
--	AND (
--		CASE 
--			WHEN S.VENUECODE IN (SELECT DISTINCT VENUECODE FROM SECURITY) 
--			THEN DATEDIFF(SECOND, S.RMSUPDTIME, V.MaxRMSUPDTIME)
--		END > @SecurityTimeDiff
--		OR DATEDIFF(SECOND, S.RMSUPDTIME, CURRENT_TIMESTAMP) > @SecurityTimeDiff
--	)
--	AND S.SESSIONENDTIME >= CAST(GETDATE() AS TIME);

--END

--GO

CREATE   PROCEDURE [dbo].[UpdateClientDetails] 
	@USERCODE varchar(20),
    @BANKDEPOSIT decimal(20,4) =0,
    @BANKWITHDRAW decimal(20,4) =0, 
	@PENDINGJOURNAL decimal(20,4) =0,

	@CREDITAPPROVED decimal(20,4)=0,
	@CREDITPERREQ decimal(20,4) = 0,

	@FIXEDBALANCE decimal(20,4) = 0,
	@EXGLATEDELIVERYVALUE decimal(18,4)=0,
	@BANKGARANTEE decimal(20,4) = 0,
	@COMPANYID int,
	@ADDMGN decimal(20,4) = 0,
	@SPANMGN decimal(20,4) = 0,
	@PORTFOLIOLOADED int,

	@ISBANK varchar(2) ='N',
	@ISCREDIT varchar(2)= 'N',
	@ISBALANCE varchar(2)='N'
AS
BEGIN
	IF @ISBANK ='Y'
	BEGIN
		insert into rmstestlog(spname,remarks)
		values('UpdateClientDetails','start-@ISBANK')
		UPDATE CLIENTDETAILS SET BANKDEPOSIT=BANKDEPOSIT+@BANKDEPOSIT,BANKWITHDRAW=BANKWITHDRAW+@BANKWITHDRAW,PENDINGJOURNAL=PENDINGJOURNAL+@PENDINGJOURNAL 
		WHERE USERCODE = @USERCODE

		RETURN
	END
	IF @ISCREDIT ='Y'
	BEGIN
		insert into rmstestlog(spname,remarks)
		values('UpdateClientDetails','start-@ISCREDIT')
		Declare @CREDITPERUSED decimal(20,4),@CREDITLIMIT decimal(20,4);
		
		SELECT @CREDITLIMIT = CREDITLIMIT FROM  CLIENTDETAILS(nolock)  WHERE USERCODE= @USERCODE

		SET @CREDITPERUSED = CASE
			WHEN  @CREDITLIMIT <> 0 AND ((@CREDITAPPROVED / 100.0) * @CREDITPERREQ) > @CREDITLIMIT THEN @CREDITLIMIT
			ELSE ISNULL((@CREDITAPPROVED / 100.0) * @CREDITPERREQ, 0) 
		END;

		UPDATE CLIENTDETAILS SET CREDITAPPROVED=CREDITAPPROVED+ @CREDITAPPROVED,CREDITPERUSED=CREDITPERUSED+ @CREDITPERUSED 
		WHERE USERCODE = @USERCODE

		SELECT @CREDITPERUSED AS creditperused, @CREDITLIMIT AS creditlimit;

		RETURN
	END
	IF @ISBALANCE ='Y'
	BEGIN
		insert into rmstestlog(spname,remarks)
		values('UpdateClientDetails','start-@ISBALANCE')
		UPDATE CLIENTDETAILS SET FIXEDBALANCE=@FIXEDBALANCE,EXGLATEDELIVERYVALUE=@EXGLATEDELIVERYVALUE,BANKGARANTEE=@BANKGARANTEE,
			COMPANYID=@COMPANYID,ADDMGN=@ADDMGN,SPANMGN=@SPANMGN,PORTFOLIOLOADED=@PORTFOLIOLOADED 
		WHERE USERCODE=@USERCODE;

		RETURN
	END
END

GO
