SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[InsertToSecurityBkup]
	@price Decimal(18,6),
	@nav Decimal(18,6),
	@CHANGE_FLAG int,
	@SUBSCRIPTION_FLAG int,
	@LASTTUPDTIME varchar(50),
	@BATCHNO int,
	@RMSUPDTIME varchar(50),
	@VENUECODE varchar(30),
	@VENUESCRIPCODE varchar(40),
	@SPOT_LASTTRADEDPRICE Decimal(20,4),
	@isNSEMF Varchar(10)
AS
BEGIN
SET NOCOUNT ON
	IF @isNSEMF = 'T'
		INSERT INTO SECURITYBKP (LASTTRADEDPRICE,CHANGE_FLAG,SUBSCRIPTION_FLAG,LASTTUPDTIME,BATCHNO,RMSUPDTIME,VENUECODE,VENUESCRIPCODE) 
			VALUES(@nav,@CHANGE_FLAG,@SUBSCRIPTION_FLAG,cast(@LASTTUPDTIME as datetime),@BATCHNO,cast(@RMSUPDTIME as datetime),@VENUECODE,@VENUESCRIPCODE);
	ELSE 
	BEGIN
	IF @price > 0
	BEGIN
		IF @SPOT_LASTTRADEDPRICE <> 0
			INSERT INTO SECURITYBKP (LASTTRADEDPRICE,CHANGE_FLAG,SUBSCRIPTION_FLAG,LASTTUPDTIME,BATCHNO,RMSUPDTIME,SPOT_LASTTRADEDPRICE,VENUECODE,VENUESCRIPCODE)
				VALUES(@price,@CHANGE_FLAG,@SUBSCRIPTION_FLAG,cast(@LASTTUPDTIME as datetime),@BATCHNO,cast(@RMSUPDTIME as datetime),@SPOT_LASTTRADEDPRICE,@VENUECODE,@VENUESCRIPCODE);
		ELSE
			INSERT INTO SECURITYBKP (LASTTRADEDPRICE,CHANGE_FLAG,SUBSCRIPTION_FLAG,LASTTUPDTIME,BATCHNO,RMSUPDTIME,VENUECODE,VENUESCRIPCODE) 
				VALUES(@price,@CHANGE_FLAG,@SUBSCRIPTION_FLAG,cast(@LASTTUPDTIME as datetime),@BATCHNO,cast(@RMSUPDTIME as datetime),@VENUECODE,@VENUESCRIPCODE);
	END
	ELSE IF @SPOT_LASTTRADEDPRICE <> 0
		INSERT INTO SECURITYBKP (CHANGE_FLAG,SUBSCRIPTION_FLAG,SPOT_LASTTRADEDPRICE,VENUECODE,VENUESCRIPCODE)
			VALUES(@CHANGE_FLAG,@SUBSCRIPTION_FLAG,@SPOT_LASTTRADEDPRICE,@VENUECODE,@VENUESCRIPCODE);
	END
END

GO
