SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[InsertToSquareofforders] 
    @ENTERINGUSERCODE varchar(20), 
	@ORDERINGUSERCODE varchar(20),
	@VENUECODE varchar(20), 
	@VENUESCRIPCODE varchar(50) ,
	@ORDERSOURCE int,
	@CHANNEL int,
	@STRIKEPRICE decimal(20,4), 
	@ORDERTYPE int,
	@SECURITYCODE varchar(20), 
	@PRODUCTTYPE int, 
	@PRICECONDITION int,
	@BUYORSELL int,
	@QTY decimal(20,4), 
	@TIFCD varchar(20), 
	@SEGMENT int,
	@INSTRUMENTTYPE varchar(20), 
	@IOC int, 
	@ORDERSUBTYPE int,
	@CALLPUT varchar(20),
	@STYLE varchar(20), 
	@SERIES varchar(20), 
	@REMARKS varchar(200), 
	@LOGINID varchar(50), 
	@SESSIONKEY varchar(200), 
	@TRANSID int,
	@LMUNIQUEID varchar(200), 
	@LASTUPDATEDON varchar(50),
	@BATCHNO int,
	@SQROFFTYPE varchar(20), 
	@TOTALMTMPER decimal(20,4), 
	@TOTALMVPER decimal(20,4), 
	@RISKMANAGEMENT int,
	@TOTALEODPER decimal(20,4), 
	@TOTALPEAKPER decimal(20,4), 
	@TOTALMTFPER decimal(20,4)
AS
BEGIN
SET NOCOUNT ON 	
insert into rmstestlog(spname,remarks)
	values('InsertToSquareofforders','start')
	INSERT INTO SQUAREOFFORDERS(ENTERINGUSERCODE, ORDERINGUSERCODE,VENUECODE, VENUESCRIPCODE ,ORDERSOURCE,CHANNEL,STRIKEPRICE, ORDERTYPE,SECURITYCODE, 
		PRODUCTTYPE, PRICECONDITION,BUYORSELL,QTY,TIFCD,SEGMENT,INSTRUMENTTYPE,IOC, ORDERSUBTYPE,CALLPUT,STYLE ,SERIES,REMARKS,LOGINID,SESSIONKEY,TRANSID,
		LMUNIQUEID,LASTUPDATEDON,BATCHNO,SQROFFTYPE,TOTALMTMPER, TOTALMVPER,RISKMANAGEMENT ,STATUS,MAILSEND,TOTALEODPER,TOTALPEAKPER,TOTALMTFPER) 
	VALUES (@ENTERINGUSERCODE, @ORDERINGUSERCODE,@VENUECODE, @VENUESCRIPCODE ,@ORDERSOURCE,@CHANNEL,@STRIKEPRICE, @ORDERTYPE,@SECURITYCODE, 
		@PRODUCTTYPE, @PRICECONDITION,@BUYORSELL,@QTY,@TIFCD,@SEGMENT,@INSTRUMENTTYPE,@IOC, @ORDERSUBTYPE,@CALLPUT,@STYLE ,@SERIES,@REMARKS,@LOGINID,@SESSIONKEY,@TRANSID,
		@LMUNIQUEID,CAST(@LASTUPDATEDON AS DATETIME),@BATCHNO,@SQROFFTYPE,@TOTALMTMPER, @TOTALMVPER,@RISKMANAGEMENT,1,0,@TOTALEODPER,@TOTALPEAKPER,@TOTALMTFPER)
END

GO
