SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--CREATE OR ALTER PROCEDURE dbo.UpdateClients 
--	@USERCODE varchar(20),
--  @FIXEDBALANCE decimal(20,4) ,
--	@EXGLATEDELIVERYVALUE decimal(20,4),
--	@BANKGARANTEE decimal(20,4),
--	@COMPANYID int,
--	@ADDMGN decimal(20,4),
--	@SPANMGN decimal(20,4),
--	@PORTFOLIOLOADED int,
--	@ADDMGN_NCDEX decimal(20,4),
--	@SPANMARGIN_NCDEX decimal(20,4),
--	@ADDMGN_MCX decimal(20,4),
--	@SPANMARGIN_MCX  decimal(20,4),
--	@ADDMGN_NSECOM  decimal(20,4),
--	@SPANMARGIN_NSECOM decimal(20,4),
--	@ADDMGN_NSECD decimal(20,4),
--	@SPANMARGIN_NSECD decimal(20,4),
--	@ADDMGN_NSEFO decimal(20,4),
--	@SPANMARGIN_NSEFO decimal(20,4),
--	@ADDMGN_NCDEX_INTRADAY decimal(20,4),
--	@ADDMGN_MCX_INTRADAY decimal(20,4),
--	@ADDMGN_NSEFO_INTRADAY decimal(20,4),
--	@ADDMGN_NSECD_INTRADAY decimal(20,4)
--AS
--BEGIN
--SET NOCOUNT ON	
--	UPDATE CLIENTDETAILS SET FIXEDBALANCE=@FIXEDBALANCE,EXGLATEDELIVERYVALUE=@EXGLATEDELIVERYVALUE,BANKGARANTEE=@BANKGARANTEE,COMPANYID=@COMPANYID,
--			ADDMGN=@ADDMGN,SPANMGN=@SPANMGN,PORTFOLIOLOADED=@PORTFOLIOLOADED,ADDMGN_NCDEX=@ADDMGN_NCDEX,SPANMARGIN_NCDEX=@SPANMARGIN_NCDEX,
--			ADDMGN_MCX=@ADDMGN_MCX,SPANMARGIN_MCX=@SPANMARGIN_MCX,ADDMGN_NSECOM=@ADDMGN_NSECOM,SPANMARGIN_NSECOM=@SPANMARGIN_NSECOM,
--			ADDMGN_NSECD=@ADDMGN_NSECD,SPANMARGIN_NSECD=@SPANMARGIN_NSECD,ADDMGN_NSEFO=@ADDMGN_NSEFO,SPANMARGIN_NSEFO=@SPANMARGIN_NSEFO,
--			ADDMGN_NCDEX_INTRADAY=@ADDMGN_NCDEX_INTRADAY,ADDMGN_MCX_INTRADAY=@ADDMGN_MCX_INTRADAY,
--			ADDMGN_NSEFO_INTRADAY=@ADDMGN_NSEFO_INTRADAY,ADDMGN_NSECD_INTRADAY=@ADDMGN_NSECD_INTRADAY 
--	WHERE USERCODE=@USERCODE

--END

--GO

CREATE   PROCEDURE [dbo].[getClientPortfolio]
    @usercode varchar(20),
	@PORTFOLIOTYPE int,
	@VENUECODE varchar(30),
	@VENUESCRIPCODE varchar(50)
AS
BEGIN
SET NOCOUNT ON
insert into rmstestlog(spname,remarks)
	values('getClientPortfolio','start')
	SELECT  * FROM  PORTFOLIO(nolock)  
	WHERE usercode=@usercode and PORTFOLIOTYPE =@PORTFOLIOTYPE and VENUECODE =@VENUECODE and VENUESCRIPCODE = @VENUESCRIPCODE 
END

GO
