SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[GetOrderCount] 
    @ORDERINGUSERCODE varchar(30),
	@PRODUCTTYPE int,
	@VENUECODE varchar(30),
	@VENUESCRIPCODE varchar(50)

AS
BEGIN
SET NOCOUNT ON
insert into rmstestlog(spname,remarks)
	values('GetOrderCount','start')

	SELECT COUNT(*) AS ORDERCOUNT FROM SQUAREOFFORDERS (NOLOCK)
	WHERE ORDERINGUSERCODE = @ORDERINGUSERCODE AND PRODUCTTYPE = @PRODUCTTYPE AND 
	VENUECODE = @VENUECODE AND VENUESCRIPCODE = @VENUESCRIPCODE AND STATUS=1
END
GO
