SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE   PROCEDURE [dbo].[UpdateClbvCount] 
	@TRANSID int
AS
BEGIN
SET NOCOUNT ON
	insert into rmstestlog(spname,remarks)
	values('UpdateClbvCount','start')
Declare @USERCODE varchar(30),
	@VENUECODE	varchar(20),
	@VENUESCRIPCODE	varchar(50),
	@PORTFOLIOTYPE int;

	Select @USERCODE=ORDERINGUSERCODE ,@VENUECODE=VENUECODE ,@VENUESCRIPCODE=VENUESCRIPCODE ,@PORTFOLIOTYPE=PRODUCTTYPE  
	from SQUAREOFFORDERS(nolock) where TRANSID = @TRANSID

	UPDATE PORTFOLIO SET CLBVCOUNT = CLBVCOUNT+1 
	WHERE USERCODE = @USERCODE and VENUECODE = @VENUECODE and VENUESCRIPCODE = @VENUESCRIPCODE and PORTFOLIOTYPE = @PORTFOLIOTYPE

END

GO
